import os
import json
from newspaper import Article

class NewsCleaner:
    def __init__(self, fallback_publisher: str = "CNN"):
        """
        Initializes the NewsCleaner.
        
        Args:
            fallback_publisher: The default publisher to assign if metadata is missing.
                                (e.g., "CNN" for the NewsQA dataset).
        """

        self.fallback_publisher = fallback_publisher

    def clean_html_string(self, raw_html: str, source_url: str = "http://www.dummy-news-url.com/") -> dict:
        """
        Extracts clean plain text and metadata from a raw HTML string using the newspaper3k library.
        
        Args:
            raw_html (str): The raw HTML content of the news article.
            source_url (str, optional): A dummy or real URL required by the newspaper3k 
                                        parser to initialize. Defaults to a dummy URL.
                                        
        Returns:
            dict: A structured dictionary containing:
                  - 'text' (str): The extracted, cleaned article body.
                  - 'metadata' (dict): Extracted metadata including 'title', 'url', 
                                       'publish_date', 'author', and 'publisher'.
        """

        # Initialize newspaper3k Article
        article = Article(url=source_url)
        article.set_html(raw_html)
        article.parse()

        # Extract standard metadata
        title = article.title if article.title else "Unknown Title"
        author = ", ".join(article.authors) if article.authors else "Unknown Author"
        publish_date = str(article.publish_date)[:10] if article.publish_date else "Unknown Date"

        # Extract deep metadata (URL and Publisher)
        meta_data = article.meta_data
        url = meta_data.get('og', {}).get('url', "Unknown URL")
        publisher = meta_data.get('og', {}).get('site_name', "Unknown Publisher")
        
        # Apply fallback logic if publisher isn't found
        if publisher == "Unknown Publisher":
            publisher = self.fallback_publisher

        clean_text = article.text

        return {
            "text": clean_text,
            "metadata": {
                "title": title,
                "url": url,
                "publish_date": publish_date,
                "author": author,
                "publisher": publisher
            }
        }

    def clean_file(self, file_path: str) -> dict:
        """
        Reads a local HTML file from the disk and processes it to extract clean text and metadata.
        
        Args:
            file_path (str): The absolute or relative path to the raw HTML file.
            
        Returns:
            dict: The structured dictionary containing 'text' and 'metadata', 
                  generated by the `clean_html_string` method.
        """

        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                raw_html = f.read()
        except UnicodeDecodeError:
            # Some scraped articles are actually cp1252/Latin-1, not UTF-8
            # (e.g. curly quotes, non-breaking spaces from Windows-authored pages).
            with open(file_path, 'r', encoding='cp1252') as f:
                raw_html = f.read()

        return self.clean_html_string(raw_html)

    def process_directory(self, input_dir: str, output_dir: str):
        """
        Iterates through a directory of raw HTML files, cleans them, and saves the 
        extracted text and metadata as JSON files in an output directory.
        
        Args:
            input_dir (str): The directory path containing the raw .html files.
            output_dir (str): The directory path where the processed .json files will be saved.
                              (The directory is created automatically if it does not exist).
                              
        Returns:
            None: Outputs are written directly to the filesystem.
        """

        os.makedirs(output_dir, exist_ok=True)
        
        for filename in os.listdir(input_dir):
            if filename.endswith(".html"):
                input_path = os.path.join(input_dir, filename)
                
                try:
                    article_data = self.clean_file(input_path)
                    
                    # Check if text was actually extracted
                    if not article_data["text"].strip():
                        print(f"⚠️ Warning: No text extracted from {filename}. Skipping.")
                        continue
                    
                    # Save as JSON
                    output_filename = filename.replace(".html", "_clean.json")
                    output_path = os.path.join(output_dir, output_filename)
                    
                    with open(output_path, 'w', encoding='utf-8') as f:
                        json.dump(article_data, f, indent=4, ensure_ascii=False)
                        
                    print(f"✅ Successfully cleaned: {filename}")
                    
                except Exception as e:
                    print(f"❌ Error processing {filename}: {e}")